name: Deploy CloudFormation Stack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/demo-alb-cft
        aws-region: us-east-1

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file templates/alb.yaml \
          --stack-name demo-alb \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            VpcId=${{ secrets.AWS_VPC_ID }} \
            Subnet1=${{ secrets.AWS_SUBNET1_ID }} \
            Subnet2=${{ secrets.AWS_SUBNET2_ID }} \
            KeyName=${{ secrets.AWS_KEY_PAIR }} \
            AMIId=${{ secrets.AWS_AMI_ID }}
